version: "3.8"
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: ai_faq_db
    environment:
      POSTGRES_USER: faq
      POSTGRES_PASSWORD: faqpass
      POSTGRES_DB: faqdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U faq -d faqdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  ollama:
    image: ollama/ollama:latest
    container_name: ai_faq_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  api:
    build: ./backend
    container_name: ai_faq_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./data:/app/data
      - ./backend/app:/app/app
      - chroma_data:/app/chroma_db  # ChromaDB verileri için volume

volumes:
  dbdata:
  ollama:
  chroma_data:  # ChromaDB volume tanımı